name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          dispatch-method: "workflow_dispatch"
          repo: "${{ github.event.repository.name }}"
          owner: "${{ github.repository_owner }}"
          ref: "main"
          workflow: "dispatch.yml"
          token: "${{ secrets.GITHUB_TOKEN }}"
